package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * Acesso generated by hbm2java
 */
public class Acesso  implements java.io.Serializable {


     private Integer idAcesso;
     private Colaborador colaborador;
     private String nivelAcesso;

    public Acesso() {
    }

	
    public Acesso(Colaborador colaborador) {
        this.colaborador = colaborador;
    }
    public Acesso(Colaborador colaborador, String nivelAcesso) {
       this.colaborador = colaborador;
       this.nivelAcesso = nivelAcesso;
    }
   
    public Integer getIdAcesso() {
        return this.idAcesso;
    }
    
    public void setIdAcesso(Integer idAcesso) {
        this.idAcesso = idAcesso;
    }
    public Colaborador getColaborador() {
        return this.colaborador;
    }
    
    public void setColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
    }
    public String getNivelAcesso() {
        return this.nivelAcesso;
    }
    
    public void setNivelAcesso(String nivelAcesso) {
        this.nivelAcesso = nivelAcesso;
    }




}


