package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agendamento generated by hbm2java
 */
public class Agendamento  implements java.io.Serializable {


     private Integer idAgendamento;
     private Cliente cliente;
     private Colaborador colaborador;
     private Servico servico;
     private ServicoTerceiro servicoTerceiro;
     private String hora;
     private Date data;
     private Integer transacao;
     private Integer status;
     private Byte operacao;
     private String observacoes;
     private Double valorTotal;
     private Set tblAssocCliAgendas = new HashSet(0);

    public Agendamento() {
    }
    
     public String[] getAgenda(){
        String servico = "", funcionario = "", status = "";
        double valor = 0.0;
        
        if(operacao == 1){
            funcionario = this.colaborador.getPessoa().getNome();
            servico = this.servico.getNomeServico();
            valor = this.servico.getValorTotal();
        }else if(operacao == 2){
            funcionario = "T: "+this.servicoTerceiro.getTerceiro().getPessoa().getNome();
            servico = "T: "+this.servicoTerceiro.getNomeServico();
            valor = this.servicoTerceiro.getValorServ();
        }
        
        if(this.status == 0){
            status = "Agendado";
        }else  if(this.status == 1){
            status = "Confirmado";
        }else  if(this.status == 2){
            status = "Concluido";
        }
        
        
        return new String[]{
            
            cliente.getPessoa().getNome(),
            funcionario,
            servico,
            status,
            String.valueOf(valor),
        };
    }
    
    public String[] getAgendaVoid(){
        return new String[]{
            "",
            "",
            "",
            "",
            "",
        };
    }

	
    public Agendamento(Cliente cliente) {
        this.cliente = cliente;
    }
    public Agendamento(Cliente cliente, Colaborador colaborador, Servico servico, ServicoTerceiro servicoTerceiro, String hora, Date data, Integer transacao, Integer status, Byte operacao, String observacoes, Double valorTotal, Set tblAssocCliAgendas) {
       this.cliente = cliente;
       this.colaborador = colaborador;
       this.servico = servico;
       this.servicoTerceiro = servicoTerceiro;
       this.hora = hora;
       this.data = data;
       this.transacao = transacao;
       this.status = status;
       this.operacao = operacao;
       this.observacoes = observacoes;
       this.valorTotal = valorTotal;
       this.tblAssocCliAgendas = tblAssocCliAgendas;
    }
   
    public Integer getIdAgendamento() {
        return this.idAgendamento;
    }
    
    public void setIdAgendamento(Integer idAgendamento) {
        this.idAgendamento = idAgendamento;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Colaborador getColaborador() {
        return this.colaborador;
    }
    
    public void setColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }
    public ServicoTerceiro getServicoTerceiro() {
        return this.servicoTerceiro;
    }
    
    public void setServicoTerceiro(ServicoTerceiro servicoTerceiro) {
        this.servicoTerceiro = servicoTerceiro;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getTransacao() {
        return this.transacao;
    }
    
    public void setTransacao(Integer transacao) {
        this.transacao = transacao;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Byte getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(Byte operacao) {
        this.operacao = operacao;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Set getTblAssocCliAgendas() {
        return this.tblAssocCliAgendas;
    }
    
    public void setTblAssocCliAgendas(Set tblAssocCliAgendas) {
        this.tblAssocCliAgendas = tblAssocCliAgendas;
    }




}


