package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaProduto generated by hbm2java
 */
public class CategoriaProduto  implements java.io.Serializable {


     private Integer idCategoria;
     private String nomeCategoria;
     private Set produtos = new HashSet(0);

    public CategoriaProduto() {
    }

    public CategoriaProduto(String nomeCategoria, Set produtos) {
       this.nomeCategoria = nomeCategoria;
       this.produtos = produtos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNomeCategoria() {
        return this.nomeCategoria;
    }
    
    public void setNomeCategoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


