package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Colaborador generated by hbm2java
 */
public class Colaborador  implements java.io.Serializable {


     private Integer idColaborador;
     private Pessoa pessoa;
     private Usuarios usuarios;
     private int idade;
     private String sexo;
     private String especialidade;
     private String descricaoFormacao;
     private Set acessos = new HashSet(0);
     private Set agendamentos = new HashSet(0);
     private Set tblAssosiativaServicoses = new HashSet(0);

    public Colaborador() {
    }
    
    public String[] getColaborador(){
        
        return new String[]{
                pessoa.getNome(),
                pessoa.getCpfCnpj(),
                this.sexo,
                String.valueOf(this.idade),
                pessoa.getTelefone(),
                especialidade,
                pessoa.getEndereco().getRua(),
                String.valueOf(pessoa.getEndereco().getNumero()),
                pessoa.getEndereco().getCidades().getNomeCidade(),
                pessoa.getEndereco().getCidades().getEstado().getSigla()
                
                
        };
    }

    public String[] getColaboradorAgenda(){
        
        return new String[]{
                
                 String.valueOf(idColaborador),
                pessoa.getNome(),
                pessoa.getCpfCnpj(),
                pessoa.getTelefone(),
                especialidade,
                
        };
    }

	
    public Colaborador(Pessoa pessoa, Usuarios usuarios, int idade, String especialidade) {
        this.pessoa = pessoa;
        this.usuarios = usuarios;
        this.idade = idade;
        this.especialidade = especialidade;
    }
    public Colaborador(Pessoa pessoa, Usuarios usuarios, int idade, String sexo, String especialidade, String descricaoFormacao, Set acessos, Set agendamentos, Set tblAssosiativaServicoses) {
       this.pessoa = pessoa;
       this.usuarios = usuarios;
       this.idade = idade;
       this.sexo = sexo;
       this.especialidade = especialidade;
       this.descricaoFormacao = descricaoFormacao;
       this.acessos = acessos;
       this.agendamentos = agendamentos;
       this.tblAssosiativaServicoses = tblAssosiativaServicoses;
    }
   
    public Integer getIdColaborador() {
        return this.idColaborador;
    }
    
    public void setIdColaborador(Integer idColaborador) {
        this.idColaborador = idColaborador;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public String getDescricaoFormacao() {
        return this.descricaoFormacao;
    }
    
    public void setDescricaoFormacao(String descricaoFormacao) {
        this.descricaoFormacao = descricaoFormacao;
    }
    public Set getAcessos() {
        return this.acessos;
    }
    
    public void setAcessos(Set acessos) {
        this.acessos = acessos;
    }
    public Set getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Set agendamentos) {
        this.agendamentos = agendamentos;
    }
    public Set getTblAssosiativaServicoses() {
        return this.tblAssosiativaServicoses;
    }
    
    public void setTblAssosiativaServicoses(Set tblAssosiativaServicoses) {
        this.tblAssosiativaServicoses = tblAssosiativaServicoses;
    }




}


