package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private Cidades cidades;
     private String rua;
     private int numero;
     private String bairro;
     private String cep;
     private Set fornecedors = new HashSet(0);
     private Set pessoas = new HashSet(0);

    public Endereco() {
    }

	
    public Endereco(Cidades cidades, String rua, int numero, String cep) {
        this.cidades = cidades;
        this.rua = rua;
        this.numero = numero;
        this.cep = cep;
    }
    public Endereco(Cidades cidades, String rua, int numero, String bairro, String cep, Set fornecedors, Set pessoas) {
       this.cidades = cidades;
       this.rua = rua;
       this.numero = numero;
       this.bairro = bairro;
       this.cep = cep;
       this.fornecedors = fornecedors;
       this.pessoas = pessoas;
    }
   
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }
    public Cidades getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Cidades cidades) {
        this.cidades = cidades;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


