package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private String sigla;
     private String nomeEstado;
     private Set cidadeses = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int idEstado, String sigla, String nomeEstado) {
        this.idEstado = idEstado;
        this.sigla = sigla;
        this.nomeEstado = nomeEstado;
    }
    public Estado(int idEstado, String sigla, String nomeEstado, Set cidadeses) {
       this.idEstado = idEstado;
       this.sigla = sigla;
       this.nomeEstado = nomeEstado;
       this.cidadeses = cidadeses;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public String getNomeEstado() {
        return this.nomeEstado;
    }
    
    public void setNomeEstado(String nomeEstado) {
        this.nomeEstado = nomeEstado;
    }
    public Set getCidadeses() {
        return this.cidadeses;
    }
    
    public void setCidadeses(Set cidadeses) {
        this.cidadeses = cidadeses;
    }




}


