package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ficha generated by hbm2java
 */
public class Ficha  implements java.io.Serializable {


     private Integer idFicha;
     private Cliente cliente;
     private byte saude;
     private byte SCabelo;
     private byte SCor;
     private Byte SProdCasa;
     private Set tblAssocSaudes = new HashSet(0);
     private Set tblAssocTpCabelos = new HashSet(0);
     private Set tblAssocCors = new HashSet(0);
     private Set tblAssocProdCasas = new HashSet(0);

    public Ficha() {
    }

	
    public Ficha(Cliente cliente, byte saude, byte SCabelo, byte SCor) {
        this.cliente = cliente;
        this.saude = saude;
        this.SCabelo = SCabelo;
        this.SCor = SCor;
    }
    public Ficha(Cliente cliente, byte saude, byte SCabelo, byte SCor, Byte SProdCasa, Set tblAssocSaudes, Set tblAssocTpCabelos, Set tblAssocCors, Set tblAssocProdCasas) {
       this.cliente = cliente;
       this.saude = saude;
       this.SCabelo = SCabelo;
       this.SCor = SCor;
       this.SProdCasa = SProdCasa;
       this.tblAssocSaudes = tblAssocSaudes;
       this.tblAssocTpCabelos = tblAssocTpCabelos;
       this.tblAssocCors = tblAssocCors;
       this.tblAssocProdCasas = tblAssocProdCasas;
    }
   
    public Integer getIdFicha() {
        return this.idFicha;
    }
    
    public void setIdFicha(Integer idFicha) {
        this.idFicha = idFicha;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public byte getSaude() {
        return this.saude;
    }
    
    public void setSaude(byte saude) {
        this.saude = saude;
    }
    public byte getSCabelo() {
        return this.SCabelo;
    }
    
    public void setSCabelo(byte SCabelo) {
        this.SCabelo = SCabelo;
    }
    public byte getSCor() {
        return this.SCor;
    }
    
    public void setSCor(byte SCor) {
        this.SCor = SCor;
    }
    public Byte getSProdCasa() {
        return this.SProdCasa;
    }
    
    public void setSProdCasa(Byte SProdCasa) {
        this.SProdCasa = SProdCasa;
    }
    public Set getTblAssocSaudes() {
        return this.tblAssocSaudes;
    }
    
    public void setTblAssocSaudes(Set tblAssocSaudes) {
        this.tblAssocSaudes = tblAssocSaudes;
    }
    public Set getTblAssocTpCabelos() {
        return this.tblAssocTpCabelos;
    }
    
    public void setTblAssocTpCabelos(Set tblAssocTpCabelos) {
        this.tblAssocTpCabelos = tblAssocTpCabelos;
    }
    public Set getTblAssocCors() {
        return this.tblAssocCors;
    }
    
    public void setTblAssocCors(Set tblAssocCors) {
        this.tblAssocCors = tblAssocCors;
    }
    public Set getTblAssocProdCasas() {
        return this.tblAssocProdCasas;
    }
    
    public void setTblAssocProdCasas(Set tblAssocProdCasas) {
        this.tblAssocProdCasas = tblAssocProdCasas;
    }




}


