package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer idFornecedor;
     private Endereco endereco;
     private String razaoSocial;
     private String nomeFantasia;
     private String email;
     private String cnpjCpf;
     private String telefone;
     private String responsavel;
     private Set pedidoCompras = new HashSet(0);

    public Fornecedor() {
    }
    
     public String[] getFornecedor(){
        
        return new String[]{
                razaoSocial,
                cnpjCpf,
                nomeFantasia,
                email,
                telefone,
                endereco.getRua(),
                String.valueOf(endereco.getNumero()),
                endereco.getCidades().getNomeCidade(),
                endereco.getCidades().getEstado().getSigla()
        };
    }

	
    public Fornecedor(Endereco endereco, String razaoSocial, String cnpjCpf, String responsavel) {
        this.endereco = endereco;
        this.razaoSocial = razaoSocial;
        this.cnpjCpf = cnpjCpf;
        this.responsavel = responsavel;
    }
    public Fornecedor(Endereco endereco, String razaoSocial, String nomeFantasia, String email, String cnpjCpf, String telefone, String responsavel, Set pedidoCompras) {
       this.endereco = endereco;
       this.razaoSocial = razaoSocial;
       this.nomeFantasia = nomeFantasia;
       this.email = email;
       this.cnpjCpf = cnpjCpf;
       this.telefone = telefone;
       this.responsavel = responsavel;
       this.pedidoCompras = pedidoCompras;
    }
   
    public Integer getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(Integer idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCnpjCpf() {
        return this.cnpjCpf;
    }
    
    public void setCnpjCpf(String cnpjCpf) {
        this.cnpjCpf = cnpjCpf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(String responsavel) {
        this.responsavel = responsavel;
    }
    public Set getPedidoCompras() {
        return this.pedidoCompras;
    }
    
    public void setPedidoCompras(Set pedidoCompras) {
        this.pedidoCompras = pedidoCompras;
    }




}


