package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private Endereco endereco;
     private String nome;
     private String rg;
     private String cpfCnpj;
     private String telefone;
     private String observacoes;
     private Set clientes = new HashSet(0);
     private Set colaboradors = new HashSet(0);
     private Set terceiros = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(Endereco endereco, String nome, String cpfCnpj, String telefone) {
        this.endereco = endereco;
        this.nome = nome;
        this.cpfCnpj = cpfCnpj;
        this.telefone = telefone;
    }
    public Pessoa(Endereco endereco, String nome, String rg, String cpfCnpj, String telefone, String observacoes, Set clientes, Set colaboradors, Set terceiros) {
       this.endereco = endereco;
       this.nome = nome;
       this.rg = rg;
       this.cpfCnpj = cpfCnpj;
       this.telefone = telefone;
       this.observacoes = observacoes;
       this.clientes = clientes;
       this.colaboradors = colaboradors;
       this.terceiros = terceiros;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set colaboradors) {
        this.colaboradors = colaboradors;
    }
    public Set getTerceiros() {
        return this.terceiros;
    }
    
    public void setTerceiros(Set terceiros) {
        this.terceiros = terceiros;
    }




}


