package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProblemasSaude generated by hbm2java
 */
public class ProblemasSaude  implements java.io.Serializable {


     private Integer idProblemas;
     private String tipoProblema;
     private Set tblAssocSaudes = new HashSet(0);

    public ProblemasSaude() {
    }

	
    public ProblemasSaude(String tipoProblema) {
        this.tipoProblema = tipoProblema;
    }
    public ProblemasSaude(String tipoProblema, Set tblAssocSaudes) {
       this.tipoProblema = tipoProblema;
       this.tblAssocSaudes = tblAssocSaudes;
    }
   
    public Integer getIdProblemas() {
        return this.idProblemas;
    }
    
    public void setIdProblemas(Integer idProblemas) {
        this.idProblemas = idProblemas;
    }
    public String getTipoProblema() {
        return this.tipoProblema;
    }
    
    public void setTipoProblema(String tipoProblema) {
        this.tipoProblema = tipoProblema;
    }
    public Set getTblAssocSaudes() {
        return this.tblAssocSaudes;
    }
    
    public void setTblAssocSaudes(Set tblAssocSaudes) {
        this.tblAssocSaudes = tblAssocSaudes;
    }




}


