package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private CategoriaProduto categoriaProduto;
     private PedidoCompra pedidoCompra;
     private String nome;
     private String fabricante;
     private double valorCompra;
     private double valorVenda;
     private int unidadeDeMedida;
     private double quantidade;
     private Date dataValidade;
     private String observacoes;
     private byte SPedido;
     private Integer transacao;
     private double valorTotal;
     private double quantidadeMedida;
     private Set estoques = new HashSet(0);

    public Produto() {
    }
    
    public String[] getProduto(){
        String unidade = "";
        
        if(unidadeDeMedida == 1){
            unidade = "kg";
        }else if(unidadeDeMedida == 2){
            unidade = "ml";
        }else if(unidadeDeMedida == 3){
            unidade = "un";
        }

        
        return new String[]{
            
                nome,
                fabricante,
                String.valueOf(valorCompra),
                String.valueOf(valorVenda),
                unidade,
                dataValidade.toString(),
                String.valueOf(quantidade),
                
        };
    }

	
    public Produto(CategoriaProduto categoriaProduto, PedidoCompra pedidoCompra, String nome, String fabricante, double valorCompra, double valorVenda, int unidadeDeMedida, double quantidade, Date dataValidade, byte SPedido, double valorTotal, double quantidadeMedida) {
        this.categoriaProduto = categoriaProduto;
        this.pedidoCompra = pedidoCompra;
        this.nome = nome;
        this.fabricante = fabricante;
        this.valorCompra = valorCompra;
        this.valorVenda = valorVenda;
        this.unidadeDeMedida = unidadeDeMedida;
        this.quantidade = quantidade;
        this.dataValidade = dataValidade;
        this.SPedido = SPedido;
        this.valorTotal = valorTotal;
        this.quantidadeMedida = quantidadeMedida;
    }
    public Produto(CategoriaProduto categoriaProduto, PedidoCompra pedidoCompra, String nome, String fabricante, double valorCompra, double valorVenda, int unidadeDeMedida, double quantidade, Date dataValidade, String observacoes, byte SPedido, Integer transacao, double valorTotal, double quantidadeMedida, Set estoques) {
       this.categoriaProduto = categoriaProduto;
       this.pedidoCompra = pedidoCompra;
       this.nome = nome;
       this.fabricante = fabricante;
       this.valorCompra = valorCompra;
       this.valorVenda = valorVenda;
       this.unidadeDeMedida = unidadeDeMedida;
       this.quantidade = quantidade;
       this.dataValidade = dataValidade;
       this.observacoes = observacoes;
       this.SPedido = SPedido;
       this.transacao = transacao;
       this.valorTotal = valorTotal;
       this.quantidadeMedida = quantidadeMedida;
       this.estoques = estoques;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public CategoriaProduto getCategoriaProduto() {
        return this.categoriaProduto;
    }
    
    public void setCategoriaProduto(CategoriaProduto categoriaProduto) {
        this.categoriaProduto = categoriaProduto;
    }
    public PedidoCompra getPedidoCompra() {
        return this.pedidoCompra;
    }
    
    public void setPedidoCompra(PedidoCompra pedidoCompra) {
        this.pedidoCompra = pedidoCompra;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public double getValorCompra() {
        return this.valorCompra;
    }
    
    public void setValorCompra(double valorCompra) {
        this.valorCompra = valorCompra;
    }
    public double getValorVenda() {
        return this.valorVenda;
    }
    
    public void setValorVenda(double valorVenda) {
        this.valorVenda = valorVenda;
    }
    public int getUnidadeDeMedida() {
        return this.unidadeDeMedida;
    }
    
    public void setUnidadeDeMedida(int unidadeDeMedida) {
        this.unidadeDeMedida = unidadeDeMedida;
    }
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public byte getSPedido() {
        return this.SPedido;
    }
    
    public void setSPedido(byte SPedido) {
        this.SPedido = SPedido;
    }
    public Integer getTransacao() {
        return this.transacao;
    }
    
    public void setTransacao(Integer transacao) {
        this.transacao = transacao;
    }
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }
    public double getQuantidadeMedida() {
        return this.quantidadeMedida;
    }
    
    public void setQuantidadeMedida(double quantidadeMedida) {
        this.quantidadeMedida = quantidadeMedida;
    }
    public Set getEstoques() {
        return this.estoques;
    }
    
    public void setEstoques(Set estoques) {
        this.estoques = estoques;
    }




}


