package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProdutosCasa generated by hbm2java
 */
public class ProdutosCasa  implements java.io.Serializable {


     private Integer idProdCasa;
     private String prodCasa;
     private Set tblAssocProdCasas = new HashSet(0);

    public ProdutosCasa() {
    }

	
    public ProdutosCasa(String prodCasa) {
        this.prodCasa = prodCasa;
    }
    public ProdutosCasa(String prodCasa, Set tblAssocProdCasas) {
       this.prodCasa = prodCasa;
       this.tblAssocProdCasas = tblAssocProdCasas;
    }
   
    public Integer getIdProdCasa() {
        return this.idProdCasa;
    }
    
    public void setIdProdCasa(Integer idProdCasa) {
        this.idProdCasa = idProdCasa;
    }
    public String getProdCasa() {
        return this.prodCasa;
    }
    
    public void setProdCasa(String prodCasa) {
        this.prodCasa = prodCasa;
    }
    public Set getTblAssocProdCasas() {
        return this.tblAssocProdCasas;
    }
    
    public void setTblAssocProdCasas(Set tblAssocProdCasas) {
        this.tblAssocProdCasas = tblAssocProdCasas;
    }




}


