package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServicoTerceiro generated by hbm2java
 */
public class ServicoTerceiro  implements java.io.Serializable {


     private Integer idServicoT;
     private Terceiro terceiro;
     private TipoServico tipoServico;
     private String nomeServico;
     private int tempoExec;
     private Double valorServ;
     private String descricao;
     private Set agendamentos = new HashSet(0);

    public ServicoTerceiro() {
    }
    
     public String[] getServicoTerceiro(){
        String tempo = "";
        
        if(tempoExec == 1){
            tempo = "00:30";
        }else if(tempoExec == 2){
            tempo = "01:00";
        }else if(tempoExec == 3){
            tempo = "01:30";
        }else if(tempoExec == 4){
            tempo = "02:00";
        }
        
        return new String[]{
            
                nomeServico,
                terceiro.getPessoa().getNome(),
                tipoServico.getNomeTipo(),
                tempo,
                String.valueOf(valorServ.doubleValue()),
        };
    }


	
    public ServicoTerceiro(Terceiro terceiro, TipoServico tipoServico, String nomeServico, int tempoExec) {
        this.terceiro = terceiro;
        this.tipoServico = tipoServico;
        this.nomeServico = nomeServico;
        this.tempoExec = tempoExec;
    }
    public ServicoTerceiro(Terceiro terceiro, TipoServico tipoServico, String nomeServico, int tempoExec, Double valorServ, String descricao, Set agendamentos) {
       this.terceiro = terceiro;
       this.tipoServico = tipoServico;
       this.nomeServico = nomeServico;
       this.tempoExec = tempoExec;
       this.valorServ = valorServ;
       this.descricao = descricao;
       this.agendamentos = agendamentos;
    }
   
    public Integer getIdServicoT() {
        return this.idServicoT;
    }
    
    public void setIdServicoT(Integer idServicoT) {
        this.idServicoT = idServicoT;
    }
    public Terceiro getTerceiro() {
        return this.terceiro;
    }
    
    public void setTerceiro(Terceiro terceiro) {
        this.terceiro = terceiro;
    }
    public TipoServico getTipoServico() {
        return this.tipoServico;
    }
    
    public void setTipoServico(TipoServico tipoServico) {
        this.tipoServico = tipoServico;
    }
    public String getNomeServico() {
        return this.nomeServico;
    }
    
    public void setNomeServico(String nomeServico) {
        this.nomeServico = nomeServico;
    }
    public int getTempoExec() {
        return this.tempoExec;
    }
    
    public void setTempoExec(int tempoExec) {
        this.tempoExec = tempoExec;
    }
    public Double getValorServ() {
        return this.valorServ;
    }
    
    public void setValorServ(Double valorServ) {
        this.valorServ = valorServ;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Set agendamentos) {
        this.agendamentos = agendamentos;
    }




}


