package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private Integer idServico;
     private TipoServico tipoServico;
     private String nomeServico;
     private int tempoExec;
     private Double valorServ;
     private Double valorTotal;
     private Integer semProduto;
     private Set tblAssocProdServs = new HashSet(0);
     private Set tblAssosiativaServicoses = new HashSet(0);
     private Set agendamentos = new HashSet(0);

    public Servico() {
    }
    
    
        public String[] getServico(){
        String tempo = "";
        
        if(tempoExec == 1){
            tempo = "00:30";
        }else if(tempoExec == 2){
            tempo = "01:00";
        }else if(tempoExec == 3){
            tempo = "01:30";
        }else if(tempoExec == 4){
            tempo = "02:00";
        }
        
        return new String[]{
            
                nomeServico,
                tipoServico.getNomeTipo(),
                tempo,
                String.valueOf(valorTotal.doubleValue()),
        };
    }

	
    public Servico(TipoServico tipoServico, String nomeServico, int tempoExec) {
        this.tipoServico = tipoServico;
        this.nomeServico = nomeServico;
        this.tempoExec = tempoExec;
    }
    public Servico(TipoServico tipoServico, String nomeServico, int tempoExec, Double valorServ, Double valorTotal, Integer semProduto, Set tblAssocProdServs, Set tblAssosiativaServicoses, Set agendamentos) {
       this.tipoServico = tipoServico;
       this.nomeServico = nomeServico;
       this.tempoExec = tempoExec;
       this.valorServ = valorServ;
       this.valorTotal = valorTotal;
       this.semProduto = semProduto;
       this.tblAssocProdServs = tblAssocProdServs;
       this.tblAssosiativaServicoses = tblAssosiativaServicoses;
       this.agendamentos = agendamentos;
    }
   
    public Integer getIdServico() {
        return this.idServico;
    }
    
    public void setIdServico(Integer idServico) {
        this.idServico = idServico;
    }
    public TipoServico getTipoServico() {
        return this.tipoServico;
    }
    
    public void setTipoServico(TipoServico tipoServico) {
        this.tipoServico = tipoServico;
    }
    public String getNomeServico() {
        return this.nomeServico;
    }
    
    public void setNomeServico(String nomeServico) {
        this.nomeServico = nomeServico;
    }
    public int getTempoExec() {
        return this.tempoExec;
    }
    
    public void setTempoExec(int tempoExec) {
        this.tempoExec = tempoExec;
    }
    public Double getValorServ() {
        return this.valorServ;
    }
    
    public void setValorServ(Double valorServ) {
        this.valorServ = valorServ;
    }
    public Double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Integer getSemProduto() {
        return this.semProduto;
    }
    
    public void setSemProduto(Integer semProduto) {
        this.semProduto = semProduto;
    }
    public Set getTblAssocProdServs() {
        return this.tblAssocProdServs;
    }
    
    public void setTblAssocProdServs(Set tblAssocProdServs) {
        this.tblAssocProdServs = tblAssocProdServs;
    }
    public Set getTblAssosiativaServicoses() {
        return this.tblAssosiativaServicoses;
    }
    
    public void setTblAssosiativaServicoses(Set tblAssosiativaServicoses) {
        this.tblAssosiativaServicoses = tblAssosiativaServicoses;
    }
    public Set getAgendamentos() {
        return this.agendamentos;
    }
    
    public void setAgendamentos(Set agendamentos) {
        this.agendamentos = agendamentos;
    }




}


