package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocTpCabelo generated by hbm2java
 */
public class TblAssocTpCabelo  implements java.io.Serializable {


     private TblAssocTpCabeloId id;
     private Ficha ficha;
     private TipoCabelo tipoCabelo;

    public TblAssocTpCabelo() {
    }

    public TblAssocTpCabelo(TblAssocTpCabeloId id, Ficha ficha, TipoCabelo tipoCabelo) {
       this.id = id;
       this.ficha = ficha;
       this.tipoCabelo = tipoCabelo;
    }
   
    public TblAssocTpCabeloId getId() {
        return this.id;
    }
    
    public void setId(TblAssocTpCabeloId id) {
        this.id = id;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public TipoCabelo getTipoCabelo() {
        return this.tipoCabelo;
    }
    
    public void setTipoCabelo(TipoCabelo tipoCabelo) {
        this.tipoCabelo = tipoCabelo;
    }




}


