package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;



/**
 * TblAssocProdServ generated by hbm2java
 */
public class TblAssocProdServ  implements java.io.Serializable {


     private Integer id;
     private Estoque estoque;
     private Servico servico;
     private double quantidade;
     private double valor;
     PreparedStatement pst;

    public TblAssocProdServ() {
    }
    
    
 public String[] getTblAssocProdServ(){
        return new String[]{
            String.valueOf(estoque.getIdEstoque()),
            estoque.getProduto().getNome(),
            String.valueOf(quantidade),
            String.valueOf(valor),
        };
    }
    
    public static Connection conectaBd(){
            try{

                Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/projeto","root","");

                return conexao;
            }catch(SQLException erro){
                JOptionPane.showMessageDialog(null, erro);
                return null;
            }
    }
    
    public void excluir(int id_Servico){
        String sql =" DELETE FROM `tbl_assoc_prod-serv` WHERE servico_id_servico = ?";
        
        try {
            pst = conectaBd().prepareStatement(sql);
            
            pst.setInt(1, id_Servico);
            
            pst.execute();
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }
    
    public TblAssocProdServ(Estoque estoque, Servico servico, double quantidade, double valor) {
       this.estoque = estoque;
       this.servico = servico;
       this.quantidade = quantidade;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estoque getEstoque() {
        return this.estoque;
    }
    
    public void setEstoque(Estoque estoque) {
        this.estoque = estoque;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }




}


