package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocCor generated by hbm2java
 */
public class TblAssocCor  implements java.io.Serializable {


     private TblAssocCorId id;
     private CorFio corFio;
     private Ficha ficha;

    public TblAssocCor() {
    }

    public TblAssocCor(TblAssocCorId id, CorFio corFio, Ficha ficha) {
       this.id = id;
       this.corFio = corFio;
       this.ficha = ficha;
    }
   
    public TblAssocCorId getId() {
        return this.id;
    }
    
    public void setId(TblAssocCorId id) {
        this.id = id;
    }
    public CorFio getCorFio() {
        return this.corFio;
    }
    
    public void setCorFio(CorFio corFio) {
        this.corFio = corFio;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }




}


