package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocCliAgenda generated by hbm2java
 */
public class TblAssocCliAgenda  implements java.io.Serializable {


     private Integer id;
     private Agendamento agendamento;
     private Cliente cliente;

    public TblAssocCliAgenda() {
    }

    public TblAssocCliAgenda(Agendamento agendamento, Cliente cliente) {
       this.agendamento = agendamento;
       this.cliente = cliente;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agendamento getAgendamento() {
        return this.agendamento;
    }
    
    public void setAgendamento(Agendamento agendamento) {
        this.agendamento = agendamento;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


