package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocTpCabeloId generated by hbm2java
 */
public class TblAssocTpCabeloId  implements java.io.Serializable {


     private int tipoCabeloIdTipo;
     private int fichaIdFicha;

    public TblAssocTpCabeloId() {
    }

    public TblAssocTpCabeloId(int tipoCabeloIdTipo, int fichaIdFicha) {
       this.tipoCabeloIdTipo = tipoCabeloIdTipo;
       this.fichaIdFicha = fichaIdFicha;
    }
   
    public int getTipoCabeloIdTipo() {
        return this.tipoCabeloIdTipo;
    }
    
    public void setTipoCabeloIdTipo(int tipoCabeloIdTipo) {
        this.tipoCabeloIdTipo = tipoCabeloIdTipo;
    }
    public int getFichaIdFicha() {
        return this.fichaIdFicha;
    }
    
    public void setFichaIdFicha(int fichaIdFicha) {
        this.fichaIdFicha = fichaIdFicha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAssocTpCabeloId) ) return false;
		 TblAssocTpCabeloId castOther = ( TblAssocTpCabeloId ) other; 
         
		 return (this.getTipoCabeloIdTipo()==castOther.getTipoCabeloIdTipo())
 && (this.getFichaIdFicha()==castOther.getFichaIdFicha());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTipoCabeloIdTipo();
         result = 37 * result + this.getFichaIdFicha();
         return result;
   }   


}


