package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocSaudeId generated by hbm2java
 */
public class TblAssocSaudeId  implements java.io.Serializable {


     private int problemasSaudeIdProblemas;
     private int fichaIdFicha;

    public TblAssocSaudeId() {
    }

    public TblAssocSaudeId(int problemasSaudeIdProblemas, int fichaIdFicha) {
       this.problemasSaudeIdProblemas = problemasSaudeIdProblemas;
       this.fichaIdFicha = fichaIdFicha;
    }
   
    public int getProblemasSaudeIdProblemas() {
        return this.problemasSaudeIdProblemas;
    }
    
    public void setProblemasSaudeIdProblemas(int problemasSaudeIdProblemas) {
        this.problemasSaudeIdProblemas = problemasSaudeIdProblemas;
    }
    public int getFichaIdFicha() {
        return this.fichaIdFicha;
    }
    
    public void setFichaIdFicha(int fichaIdFicha) {
        this.fichaIdFicha = fichaIdFicha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAssocSaudeId) ) return false;
		 TblAssocSaudeId castOther = ( TblAssocSaudeId ) other; 
         
		 return (this.getProblemasSaudeIdProblemas()==castOther.getProblemasSaudeIdProblemas())
 && (this.getFichaIdFicha()==castOther.getFichaIdFicha());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProblemasSaudeIdProblemas();
         result = 37 * result + this.getFichaIdFicha();
         return result;
   }   


}


