package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocCorId generated by hbm2java
 */
public class TblAssocCorId  implements java.io.Serializable {


     private int corFioIdCor;
     private int fichaIdFicha;

    public TblAssocCorId() {
    }

    public TblAssocCorId(int corFioIdCor, int fichaIdFicha) {
       this.corFioIdCor = corFioIdCor;
       this.fichaIdFicha = fichaIdFicha;
    }
   
    public int getCorFioIdCor() {
        return this.corFioIdCor;
    }
    
    public void setCorFioIdCor(int corFioIdCor) {
        this.corFioIdCor = corFioIdCor;
    }
    public int getFichaIdFicha() {
        return this.fichaIdFicha;
    }
    
    public void setFichaIdFicha(int fichaIdFicha) {
        this.fichaIdFicha = fichaIdFicha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblAssocCorId) ) return false;
		 TblAssocCorId castOther = ( TblAssocCorId ) other; 
         
		 return (this.getCorFioIdCor()==castOther.getCorFioIdCor())
 && (this.getFichaIdFicha()==castOther.getFichaIdFicha());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCorFioIdCor();
         result = 37 * result + this.getFichaIdFicha();
         return result;
   }   


}


