package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1



/**
 * TblAssocSaude generated by hbm2java
 */
public class TblAssocSaude  implements java.io.Serializable {


     private TblAssocSaudeId id;
     private Ficha ficha;
     private ProblemasSaude problemasSaude;

    public TblAssocSaude() {
    }

    public TblAssocSaude(TblAssocSaudeId id, Ficha ficha, ProblemasSaude problemasSaude) {
       this.id = id;
       this.ficha = ficha;
       this.problemasSaude = problemasSaude;
    }
   
    public TblAssocSaudeId getId() {
        return this.id;
    }
    
    public void setId(TblAssocSaudeId id) {
        this.id = id;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }
    public ProblemasSaude getProblemasSaude() {
        return this.problemasSaude;
    }
    
    public void setProblemasSaude(ProblemasSaude problemasSaude) {
        this.problemasSaude = problemasSaude;
    }




}


