package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Terceiro generated by hbm2java
 */
public class Terceiro  implements java.io.Serializable {


     private Integer idTerceiro;
     private Pessoa pessoa;
     private String especialidade;
     private String descricaoFormacao;
     private Integer status;
     private Set servicoTerceiros = new HashSet(0);

    public Terceiro() {
    }
    
     public String[] getTerceiro(){
        
        return new String[]{
                pessoa.getNome(),
                pessoa.getCpfCnpj(),
                pessoa.getTelefone(),
                especialidade,
                pessoa.getEndereco().getRua(),
                String.valueOf(pessoa.getEndereco().getNumero()),
                pessoa.getEndereco().getCidades().getNomeCidade(),
                pessoa.getEndereco().getCidades().getEstado().getSigla()
                
                
        };
    }
     
     public String[] getTerceiroAgenda(){
        
        return new String[]{
                
                String.valueOf(idTerceiro),
                pessoa.getNome(),
                pessoa.getCpfCnpj(),
                pessoa.getTelefone(),
                especialidade,
                
        };
    }
	

	
    public Terceiro(Pessoa pessoa, String especialidade) {
        this.pessoa = pessoa;
        this.especialidade = especialidade;
    }
    public Terceiro(Pessoa pessoa, String especialidade, String descricaoFormacao, Integer status, Set servicoTerceiros) {
       this.pessoa = pessoa;
       this.especialidade = especialidade;
       this.descricaoFormacao = descricaoFormacao;
       this.status = status;
       this.servicoTerceiros = servicoTerceiros;
    }
   
    public Integer getIdTerceiro() {
        return this.idTerceiro;
    }
    
    public void setIdTerceiro(Integer idTerceiro) {
        this.idTerceiro = idTerceiro;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public String getDescricaoFormacao() {
        return this.descricaoFormacao;
    }
    
    public void setDescricaoFormacao(String descricaoFormacao) {
        this.descricaoFormacao = descricaoFormacao;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getServicoTerceiros() {
        return this.servicoTerceiros;
    }
    
    public void setServicoTerceiros(Set servicoTerceiros) {
        this.servicoTerceiros = servicoTerceiros;
    }




}


