package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCabelo generated by hbm2java
 */
public class TipoCabelo  implements java.io.Serializable {


     private Integer idTipo;
     private String tipoCabelo;
     private Set tblAssocTpCabelos = new HashSet(0);

    public TipoCabelo() {
    }

	
    public TipoCabelo(String tipoCabelo) {
        this.tipoCabelo = tipoCabelo;
    }
    public TipoCabelo(String tipoCabelo, Set tblAssocTpCabelos) {
       this.tipoCabelo = tipoCabelo;
       this.tblAssocTpCabelos = tblAssocTpCabelos;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipoCabelo() {
        return this.tipoCabelo;
    }
    
    public void setTipoCabelo(String tipoCabelo) {
        this.tipoCabelo = tipoCabelo;
    }
    public Set getTblAssocTpCabelos() {
        return this.tblAssocTpCabelos;
    }
    
    public void setTblAssocTpCabelos(Set tblAssocTpCabelos) {
        this.tblAssocTpCabelos = tblAssocTpCabelos;
    }




}


