package controller;
// Generated 17/11/2017 01:21:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUser;
     private String usuario;
     private String senha;
     private String tipoDeAcesso;
     private Set colaboradors = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String usuario, String senha, String tipoDeAcesso) {
        this.usuario = usuario;
        this.senha = senha;
        this.tipoDeAcesso = tipoDeAcesso;
    }
    public Usuarios(String usuario, String senha, String tipoDeAcesso, Set colaboradors) {
       this.usuario = usuario;
       this.senha = senha;
       this.tipoDeAcesso = tipoDeAcesso;
       this.colaboradors = colaboradors;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getTipoDeAcesso() {
        return this.tipoDeAcesso;
    }
    
    public void setTipoDeAcesso(String tipoDeAcesso) {
        this.tipoDeAcesso = tipoDeAcesso;
    }
    public Set getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set colaboradors) {
        this.colaboradors = colaboradors;
    }




}


